M48
; DRILL file {KiCad 9.0.0} date 2025-03-25T13:14:26-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-25T13:14:26-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.500
%
G90
G05
T1
X77.42Y-95.44
X82.42Y-95.44
T2
X32.45Y-22.75
X32.45Y-127.25
X127.45Y-22.75
X127.45Y-127.25
M30
